### ISSUE TITLE
Inferred unknown and any partner gene fusions

### ISSUE THREAD

**Issue by ahwagner** [cancervariants/fusions#6]
One comment that came up during the February 10 discussion was the role of assay in determining the properties to capture for a gene fusion. There was a general opinion on the call that most assays in use today for gene fusion calling are NGS-based or FISH.

We should enumerate what these assays are: DNA-seq (targeted, exome, WGS), RNA-seq (targeted or full-transcriptome), FISH, or other assays. Each should be considered when creating recommendations.

EDIT: From conversation below, we have renamed this issue to "Inferred unknown and any partner gene fusions" to represent the dual contexts of unspecified partners in assayed and categorical gene fusions.

**Comment by dsonkin** [comment]
We probably should consider how fusion information should be stored in knowledgebases in order to be able to find it based on output from different fusion detection assays.

**Comment by Laveniya** [comment]
Linking in with the thread on the revision of HGVS description of fusions - as someone mentioned in the 2/10/21 call, FISH is still in use, so having the gene names in the descriptor at the DNA level would be useful for the clinicians who sign these cases out. I think integrating the salient elements (event/product/functional effect) with the type of assay used would be helpful.

**Comment by Laveniya** [comment]
Following on from the discussion this morning regarding the 'unknown' fusion partner... As an end user of these assays, I think what is being marketed as the 'fusion partner agnostic assay' is attractive to clinicians, because of the sheer number of fusions with diagnostic relevance. I think it would seem heretical to our bioinformatics colleagues, but this is often the most practical approach for clinical use. For example, pilocytic astrocytomas were first characterised with _KIAA1549-BRAF_ fusions, which was thought to be a canonical fusion for this entity. Since that time, there has been a plethora of other _BRAF_ fusions associated with pilocytic astrocytomas. I think this type of assay needs to be considered when creating the nomenclature because of its ease of clinical utility.

**Comment by ahwagner** [comment]
I agree with @Laveniya that we need a nomenclature to represent these concepts. Also, our current data model supports an _unknown_ gene concept, but we should extend to also capture the _any_ gene concept (@jsstevenson), as this semantic distinction is relevant for genomic knowledge matching.

**Comment by Laveniya** [comment]
@ahwagner Are we still looking at a symbol that could be used for the 'unknown' gene partner in an assayed gene fusion, as opposed to 'any gene'?
My understanding from the HGVS is that '**?**' is best used in the 'any gene' setting ( https://varnomen.hgvs.org/bg-material/consultation/svd-wg007/ )
A suitable symbol for the 'unknown' gene partner might be '**&**'. I have searched the HGVS site and I don't think it is used. The ampersand could take the place of the unknown gene partner. It doesn't imply that the gene is any gene, the way the question mark does. Rather, it would imply that while we know one gene partner, another gene partner is present but not identified by the assay. A mere suggestion!

**Comment by Laveniya** [comment]
Thank you Alex for explaining this to me. I am very happy to present the suggestion at the next meeting.
 I am approaching this from a clinical end-user perspective, who is more likely to be using assayed fusions, I hope that is okay.
Is there a link to the meeting where **'*'** was presented? I was thinking I should review what was previously presented and build on that, but no worries if it's not available. Thanks again, Alex.
